name: youliao
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # 路由框架 https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # Toast插件 https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.2.0

  # UI 组件库 ====================================================================
  # flukit https://github.com/flutterchina/flukit
  flukit:
  # 屏幕适配 https://github:com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^5.0.0

  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.2.1
  # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: 2.1.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^6.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/common/
    - assets/images/app/
    - assets/images/main/
    - assets/images/my/task/
